[package]
name = "ojcmp"
version = "0.2.0-alpha"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.69"
structopt = "0.3.14"
backtrace = "0.3.46"

[dev-dependencies]
rand = "0.7.3"
criterion = "0.3.2"

[[bench]]
name = "n_random"
harness = false
